### PR TITLE
fix: update asset code with localized contenthashes

### LINKED ISSUE #40: "Cannot find module" when using [contenthash], async chunks, and multi locale
Here's a failing test:

```typescript
(isWebpack5 ? test : test.skip)('async chunks', async () => {
	const built = await build(
		{
			'/src/index.js': 'export default import("./async-import").then(module => module.default);',
			'/src/async-import.js': 'export default import("./async-import2").then(module => module.default);',
			'/src/async-import2.js': 'export default __("hello-key");',
		},
		(config) => {
			config.output.filename = '[name].[contenthash].[locale].js';

			config.plugins.push(
				new WebpackLocalizeAssetsPlugin({
					locales: localesMulti,
				}),
			);
		},
	);

	const assets = Object.keys(built.stats.compilation.assets);
	const indexAsset = assets.find(a => a.includes('index') && a.includes('.en.js'));

	expect(() => built.require(`/dist/${indexAsset}`)).not.toThrow();
});
```

I get the error `Cannot find module './543.18b0bf0e0a99202fee2c.en.js'`. If you inspect the generated code, the hash in the filename doesn't match the hash in the webpack runtime. I suspect this would also occur with initial chunks when using WebpackManifestPlugin, but I haven't tested that.

I'm not exactly sure what the issue is, I'm still debugging.

### PR DESCRIPTION
**Pull request by benjamin-hodgson**
Figured I might as well fix it while I'm on the clock!

fix #40

### CODE REVIEW

File: src/multi-locale.ts [hunk 1]
```diff
@@ -217,8 +250,20 @@ export function generateLocalizedAssets<LocalizedData>(
 					sourceString,
 					fileNameTemplatePlaceholder,
 				);
+				const contentHashLocations = [...contentHashMap.entries()]
+					.flatMap(([hash, hashesByLocale]) => findSubstringLocations(sourceString, hash)
```
Comment (privatenumber) [inline src/multi-locale.ts:254]: FYI `findSubstringLocations` was designed to find every match of a substring in one iteration when I saw there was a surprisingly large performance hit when doing many string searches (asset source can be very large).

I just benchmarked this against a RegExp approach where the pattern contains all the hashes (like RealContentHashPlugin) and it's still significantly performant 🤯: https://jsben.ch/q0eng

```ts
function findPatternLocations(string, pattern) {
  pattern.lastIndex = 0;
  let indices = [];
  let match;
  while ((match = pattern.exec(text))) {
    indices.push(match.index);
  }
  return indices;
}
```

**Review by privatenumber — APPROVED** [review]
Great work! Thanks so much @benjamin-hodgson
